apiVersion: v1
kind: Template
metadata:
  name: selenium-hub
  annotations:
    description: "A Selenium Grid"
    iconClass: "icon-selenium"
    tags: "selenium,hub"
objects:

- apiVersion: v1
  kind: Service
  metadata:
    name: ${seleniumhub}
  spec:
    selector:
      type: ${seleniumhub}
    type: ClusterIP
    ports:
    - name: web
      port: 4444
      targetPort: 4444
      protocol: TCP
    - name: node
      port: 5555
      targetPort: 5555
      protocol: TCP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${seleniumhub}
  spec:
    replicas: 1
    selector:
      type: ${seleniumhub}
    template:
      metadata:
        labels:
          type: ${seleniumhub}
        name: ${seleniumhub}
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            value: ${JAVA_OPTS}
          - name: POOL_MAX
            value: ${POOL_MAX}
          - name: GRID_NEW_SESSION_WAIT_TIMEOUT
            value: ${GRID_NEW_SESSION_WAIT_TIMEOUT}
          - name: GRID_JETTY_MAX_THREADS
            value: ${GRID_JETTY_MAX_THREADS}
          - name: GRID_NODE_POLLING
            value: ${GRID_NODE_POLLING}
          - name: GRID_CLEAN_UP_CYCLE
            value: ${GRID_CLEAN_UP_CYCLE}
          - name: GRID_TIMEOUT
            value: ${GRID_TIMEOUT}
          - name: GRID_BROWSER_TIMEOUT
            value: ${GRID_BROWSER_TIMEOUT}
          - name: GRID_MAX_SESSION
            value: ${GRID_MAX_SESSION}
          - name: GRID_UNREGISTER_IF_STILL_DOWN_AFTER
            value: ${GRID_UNREGISTER_IF_STILL_DOWN_AFTER}
          image: registry.global.ccc.srvb.bo.paas.cloudcenter.corp/san-devops/selenium-hub
          name: master
          ports:
          - containerPort: 4444
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /wd/hub/status
              port: 4444
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
          livenessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
          securityContext:
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 600s
    name: ${seleniumhub}
  spec:
    host: ${HUB_ROUTE}
    port:
      targetPort: 4444
    to:
      kind: Service
      name: ${seleniumhub}
parameters:
  - name: HUB_ROUTE
    description: Route name for the Selenium Hub
    value: 
  - name: seleniumhub
    description: Selenium Hub name
  - name: JAVA_OPTS
    description: Options to pass to the java command
    value: "-Xmx512m"
  - name: POOL_MAX
    description: Max thread count for incoming and outgoing connections
    value: "60000"
  - name: GRID_NEW_SESSION_WAIT_TIMEOUT
    description: The timeout to wait for new sessions
    value: "600000"
  - name: GRID_JETTY_MAX_THREADS
    description: Max Threads for Jetty server
    value: "100"
  - name: GRID_NODE_POLLING
    description: Node Polling setting
    value: "150"
  - name: GRID_CLEAN_UP_CYCLE
    description: How long to wait until cleanup on nodes
    value: "600"
  - name: GRID_TIMEOUT
    description: The timeout for the grid
    value: "600"
  - name: GRID_BROWSER_TIMEOUT
    description: The timeout for the browser
    value: "600"
  - name: GRID_MAX_SESSION
    description: How many sessions max
    value: "10"
  - name: GRID_UNREGISTER_IF_STILL_DOWN_AFTER
    description: Time to wait before unregistering nodes
    value: "500"
