apiVersion: v1
kind: Template
metadata:
  name: selenium-node-chrome
  annotations:
    description: "Selenium Node with Google Chrome browser"
    iconClass: "icon-selenium"
    tags: "selenium,node,chrome"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${seleniumnodechrome}
  spec:
    replicas: "${{replicas}}"
    selector:
      browser: chrome
    template:
      metadata:
        name: ${seleniumnodechrome}-master
        labels:
          browser: chrome
      spec:
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        containers:
        - env:
          - name: JAVA_OPTS
            value: ${JAVA_OPTS}
          - name: HUB_PORT_4444_TCP_ADDR
            value: ${seleniumhub}
          - name: HUB_PORT_4444_TCP_PORT
            value: ${HUB_PORT_4444_TCP_PORT}
          - name: REMOTE_HOST
            value: ${REMOTE_HOST}
          - name: NODE_MAX_SESSION
            value: ${NODE_MAX_SESSION}
          - name: NODE_MAX_INSTANCES
            value: ${NODE_MAX_INSTANCES}            
          image: registry.global.ccc.srvb.bo.paas.cloudcenter.corp/san-devops/selenium-node-chrome:latest
          volumes:
            - /dev/shm:/dev/shm
          name: master
          ports:
          - containerPort: 4444
            protocol: TCP
          - containerPort: 5555
            protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 2000Mi
          securityContext:
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false  
- apiVersion: v1
  kind: Service
  metadata:
    name: ${seleniumnodechrome}
  spec:
    selector:
      browser: chrome
    type: ClusterIP
    ports:
    - name: node-port
      port: 5555
      targetPort: 5555
      protocol: TCP
    - name: node-port-grid
      port: 4444
      targetPort: 4444
      protocol: TCP
parameters:
  - name: JAVA_OPTS
    description: Options for the Java command
    value: "-Xmx512m -Dselenium.LOGGER.level=WARNING"
  - name: seleniumhub
    description: Selenium Hub name
  - name: seleniumnodechrome
    description: Selenium Node Name
  - name: replicas
    description: Number of replicas to run
    value: "2"
    required: true
  - name: HUB_PORT_4444_TCP_ADDR
    description: The Hub to connect to
    value: ""
  - name: HUB_PORT_4444_TCP_PORT
    description: The Hub port to connect to
    value: "4444"
  - name: REMOTE_HOST
    description: The remote host
    value: ""
  - name: NODE_MAX_INSTANCES
    description: Max Number os Instances
    value: "1" 
  - name: NODE_MAX_SESSION
    description: Max Number os Sessions
    value: "1" 
